server:
  port: 11000
spring:
  jpa:
    generate-ddl: 'false'
    properties:
      hibernate:
        generate_statistics: 'false'
        use_sql_comments: 'true'
        format_sql: 'true'
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: 'true'
    open-in-view: 'false'
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    password: '1234'
    username: 'poly'
    driver-class-name: 'org.mariadb.jdbc.Driver'
    url: 'jdbc:mariadb://db.k-wasm.kr:3306/myDB'
  application:
    name: KWASM-MANAGER
  boot:
    admin:
      client: # Spring Boot Actuator Admin UI Server
        url: https://manager.k-wasm.kr
Cloud:
  aws:
    s3:
      endPoint: kr.object.ncloudstorage.com
      bucket: findme
    credentials:
      secret-key: UTSgnAn1ke35fyLiqfUMCQ49nnWJBaXxwt0iJKlU
      access-key: 8dMZABPGyJBdWbx24GRR
    region:
      static: kr-standard
    stack:
      auto: 'false'
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: https://eureka.k-wasm.kr/eureka
    fetch-registry: true

