server:
  port: 11000

embedding:
  api:
    url: http://localhost:12000

spring:
  application:
    name: spring-vectordb
  data:
    mongodb:
      host: kopo-traine-my-mongodb-a4db0-100733095-958d25d77187.kr.lb.naverncp.com
      port: 27017
      database: myDB
      username: poly
      password: poly1234

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
feign:
  client:
    config:
      default:
        connectTimeout: 6000000
        readTimeout: 6000000

